var dataSet = [
  {
    name: "Tiger Nixon",
    position: "System Architect",
    salary: "$3,120",
    start_date: "2011/04/25",
    office: "Edinburgh",
    extn: 5421,
  },
  {
    name: "Harsa Summer",
    position: "Director",
    salary: "5300",
    start_date: "2011/07/25",
    office: "Edinburgh",
    extn: "8422",
  },
  {
    name: "Harsa Summer",
    position: "Director",
    salary: "5300",
    start_date: "2011/07/25",
    office: "Edinburgh",
    extn: "8422",
  },
  {
    name: "Mira Fall",
    position: "Director",
    salary: "5300",
    start_date: "2011/07/25",
    office: "Edinburgh",
    extn: "8422",
  },
  {
    name: "Mira Twain",
    position: "Director",
    salary: "5300",
    start_date: "2011/07/25",
    office: "Edinburgh",
    extn: "8422",
  },
  {
    name: "Putut Autumn",
    position: "Director",
    salary: "5300",
    start_date: "2011/07/25",
    office: "Edinburgh",
    extn: "8422",
  },
  {
    name: "Putut Autumn",
    position: "Director",
    salary: "5300",
    start_date: "2011/07/25",
    office: "Edinburgh",
    extn: "8422",
  },
  {
    name: "Putut Autumn",
    position: "Director",
    salary: "5300",
    start_date: "2011/07/25",
    office: "Edinburgh",
    extn: "8422",
  },
  {
    name: "Putut Autumn",
    position: "Director",
    salary: "5300",
    start_date: "2011/07/25",
    office: "Edinburgh",
    extn: "8422",
  },
  {
    name: "Nonik Londo",
    position: "Director",
    salary: "5300",
    start_date: "2011/07/25",
    office: "Edinburgh",
    extn: "8422",
  },
  {
    name: "Nonik Londo",
    position: "Director",
    salary: "5300",
    start_date: "2011/07/25",
    office: "Edinburgh",
    extn: "8422",
  },
  {
    name: "Nonik Londo",
    position: "Director",
    salary: "5300",
    start_date: "2011/07/25",
    office: "Edinburgh",
    extn: "8422",
  },
  {
    name: "Dewi Ari",
    position: "Director",
    salary: "5300",
    start_date: "2011/07/25",
    office: "Edinburgh",
    extn: "8422",
  },
  {
    name: "Dewi Ari",
    position: "Director",
    salary: "5300",
    start_date: "2011/07/25",
    office: "Edinburgh",
    extn: "8422",
  },
  {
    name: "Dewi Ari",
    position: "Director",
    salary: "5300",
    start_date: "2011/07/25",
    office: "Edinburgh",
    extn: "8422",
  },
  // ...
]

const table = new DataTable("#cust-table", {
  // options
  data: dataSet,
  language: {
    decimal: ",",
    thousands: ".",
  },
  scrollY: "530px",
  scrollCollapse: true,
  columns: [
    { data: "start_date", title: "Date", width: "100px" },
    { data: "extn", title: "Receipt", width: "60px" },
    { data: "name", title: "Name", width: "160px" },
    { data: "position", title: "Address", width: "200px" },
    {
      data: "salary",
      title: "Total",
      className: "dt-body-right",
      width: "100px",
    },
    { data: "office", title: "Branch" },
  ],
  fixedHeader: true,
  // orderCellsTop: true,
  dom: "Bfrtip",
  buttons: ["print", "csv"],
  pageLength: 25,
  autoWidth: false,
})
